CREATE DATABASE Minions;

USE [Minions];

CREATE TABLE [Minions](
	[Id] INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	[Age] INT NOT NULL
);

ALTER TABLE [MINIONS]
ADD [TownId] INT FOREIGN KEY REFERENCES [Towns](Id);