CREATE DATABASE [SoftUni];

USE [SoftUni];

CREATE TABLE [Towns](
	[Id] INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(30)
)

CREATE TABLE [Addresses](
	[Id] INT IDENTITY PRIMARY KEY,
	[AddressText] NVARCHAR(50),
	[TownId] INT FOREIGN KEY REFERENCES [Towns]([Id]) NOT NULL
)

CREATE TABLE [Departments](
	[Id] INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(30)
)

CREATE TABLE [Employees](
	[Id] INT IDENTITY PRIMARY KEY,
	[FirstName] NVARCHAR(30) NOT NULL,
	[MiddleName] NVARCHAR(30) NOT NULL,
	[LastName] NVARCHAR(30) NOT NULL,
	[JobTitle] NVARCHAR(30) NOT NULL,
	[DepartmentId] INT FOREIGN KEY REFERENCES [Departments]([Id]) NOT NULL,
	[HireDate] DATE NOT NULL,
	[Salary] DECIMAL NOT NULL,
	[AddressId] INT FOREIGN KEY REFERENCES [Addresses]([Id]) NOT NULL
)